[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "limit-order-protocol/=lib/limit-order-protocol/",
    "@1inch/solidity-utils/=lib/solidity-utils/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
